//Problem 1
//Write a program to print "good morning" and "welcome" continuously on
// the screen in Java using Threads

//Problem 2
//Add a sleep method in welcome thread of Q1 to delay its execution for 200 ms

//Problem 3
//Demonstrate getPriority and setPriority methods in java threads

//Problem 4
//How do you get state of a given thread in java

//Problem 5
//How do you get reference to the current thread in java

class MyNewThr1 extends Thread{
    @Override
    public void run() {
        for (int i = 0; i < 100; i++) {
            System.out.println("Good Morning :)");
        }
    }
}
class MyNewThr2 extends Thread{
    @Override
    public void run() {
        for (int i = 0; i <80; i++) {
            System.out.println("Welcome :)");
            try {
                Thread.sleep(200);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }
        }
    }
}
public class Tut_76_PracticeSet13 {
    public static void main(String[] args) {
        //Problem 1
        MyNewThr1 t1=new MyNewThr1();
        t1.start();
        MyNewThr2 t2=new MyNewThr2();
        t2.start();

        //Problem 3
        t1.setPriority(Thread.MAX_PRIORITY);
        System.out.println("Priority of t1 thread : "+t1.getPriority());

        //Problem 4
        System.out.println("State of thread t1 : "+t1.getState());

        //Problem 5
        System.out.println("Reference of current Thread  : "+Thread.currentThread());
    }
}
/*
Problem 1:
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)

Problem 2 :
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Welcome :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Good Morning :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)
Welcome :)

Problem 3 :
Priority of t1 thread : 10

Problem 4 :
State of thread t1 : TERMINATED

problem 5:
Reference of current Thread  : Thread[main,5,main]
 */